apiVersion: litmuschaos.io/v1alpha1
kind: ChaosExperiment
metadata:
  name: delay-sleep
  labels:
    name: delay-sleep
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/component: chaosexperiment
spec:
  definition:
    scope: Namespaced
    permissions:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "list"]
    image: alpine:3.20
    imagePullPolicy: IfNotPresent
    args:
      - /bin/sh
      - -c
      - |
        echo "Sleeping for ${DELAY_SECONDS} seconds"
        sleep "${DELAY_SECONDS}"
        echo "Done"
    command:
      - sh
    env:
      - name: DELAY_SECONDS
        value: "5"
    labels:
      name: delay-sleep
      app.kubernetes.io/part-of: litmus
      app.kubernetes.io/component: experiment-job

