apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-sa
  namespace: lab1
  labels:
    name: deployment-scale-delay-sa
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-scale-delay-role
  namespace: lab1
  labels:
    name: deployment-scale-delay-sa
    app.kubernetes.io/part-of: litmus
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "get", "list", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete", "deletecollection"]
  - apiGroups: ["litmuschaos.io"]
    resources: ["chaosengines", "chaosexperiments", "chaosresults", "chaosresults/finalizers"]
    verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-scale-delay-rolebinding
  namespace: lab1
  labels:
    name: deployment-scale-delay-sa
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-scale-delay-role
subjects:
  - kind: ServiceAccount
    name: chaos-sa
    namespace: lab1

