---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: general
  version: 0.1.0
  annotations:
    categories: General
    chartDescription: Injects chaos experiment
    executionPlane: "kubernetes"
spec:
  displayName: General
  categoryDescription: >
    General is an open-source grouing for automating deployment, scaling, and management of containerized applications. It groups containers that make up an application into logical units for easier management and discovery. It will install all the experiments which can be used to inject chaos into containerized applications.
  faults:
    - name: pod-autoscaler
      description: It injects pod-autoscaler chaos in a Kubernetes pod.
      displayName: "Pod Autoscaler"
    - name: delay-sleep
      description: It injects a delay into a chaos workflow
      displayName: "Delay"
  keywords:
    - Kubernetes
    - General
  maintainers:
    - name: Ethan
      email: Ethan.Waldman@balance-it-services.com
  minKubeVersion: 1.12.0
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents/#kubernetes
  icon:
    - url: https://github.com/litmuschaos/chaos-charts/blob/master/faults/kubernetes/icons/kubernetes.png
      mediatype: image/png

